### ISSUE TITLE
LCM is sometimes unexpectedly absent

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2338]
```
In file included from /Users/yosemite/workspace/mac-clang-continuous-matlab/drake/systems/plants/RigidBodyTree.cpp:1:
In file included from /Users/yosemite/workspace/mac-clang-continuous-matlab/drake/../drake/systems/plants/RigidBodyTree.h:15:
/Users/yosemite/workspace/mac-clang-continuous-matlab/drake/../drake/systems/plants/RigidBodyFrame.h:5:10: fatal error: 'drake/drakeRBSystem_export.h' file not found
#include "drake/drakeRBSystem_export.h"
         ^
1 error generated.
```

```
In file included from /Users/yosemite/workspace/mac-clang-continuous-matlab/drake/systems/plants/RigidBodyTreeURDF.cpp:7:
In file included from /Users/yosemite/workspace/mac-clang-continuous-matlab/drake/../drake/systems/plants/rigid_body_tree_urdf.h:7:
/Users/yosemite/workspace/mac-clang-continuous-matlab/drake/../drake/systems/plants/RigidBodyFrame.h:5:10: fatal error: 'drake/drakeRBSystem_export.h' file not found
#include "drake/drakeRBSystem_export.h"
         ^
1 error generated.
```

https://drake-cdash.csail.mit.edu/viewBuildError.php?onlydeltap&buildid=19459

**Comment by avalenzu** [comment]
I'm seeing this on an OSX Yosemite machine as well.

**Comment by avalenzu** [comment]
To follow up, on my machine this was caused by #2357

**Comment by david-german-tri** [comment]
#2357 resolves this opaque build failure, but does not address why LCM is sometimes absent.

**Comment by liangfok** [comment]
I believe this is a duplicate of https://github.com/RobotLocomotion/drake/issues/2341.

**Comment by david-german-tri** [comment]
Great, thanks!  Closing this one.
