### PR TITLE
Fixes #3487:  add a 'noreturn' attribute to drake's Abort() function

### LINKED ISSUE #3487: DRAKE_ABORT() should inhibit "control reaches end of non-void function" errors
`DRAKE_ABORT()` should inform the compiler that no return is going to happen, so that it doesn't require a meaningless `return BOGUS_VALUE;` statement following the abort.  Providing the `noreturn` attribute does the trick in gcc; I'm not sure about other compilers.  I.e., in `common/drake_assert.h`:

```
namespace drake {
namespace detail {
// Abort the program with an error message.
DRAKECOMMON_EXPORT
[[ noreturn ]] void Abort(const char* condition, const char* func, const char* file, int line);
}  // namespace detail
}  // namespace drake
```

### PR DESCRIPTION
**Pull request by maddog-tri**
Fixes #3487:  adding a 'noreturn' attribute to drake's Abort() function
declaration lets the compiler know that there is no coming back from
this function.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3488)

### CODE REVIEW

**Comment by liangfok** [comment]
Nice. I suppose as long as this works using `clang-3.7`, it is a strict improvement. Testing on OS X now...

**Comment by jwnimmer-tri** [comment]
@maddog-tri Here is a reference for the various ways needed to spell it:
https://github.com/foonathan/compatibility/blob/master/cpp11_lang/noreturn.cmake

**Comment by liangfok** [comment]
Yeah, I confirm that I'm unable to compile it as it is currently spelled using `clang` on OS X:

```
[ 16%] Building CXX object common/CMakeFiles/drakeCommon.dir/drake_assert.cc.o
In file included from /Users/liang/dev/drake-distro-4/drake/common/drake_assert.cc:1:
/Users/liang/dev/drake-distro-4/drake/../drake/common/drake_assert.h:74:1: error: an attribute list cannot appear here
[[ noreturn ]] void Abort(const char* condition,
^~~~~~~~~~~~~~
1 error generated.
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488#-:-KRsNqGDYNhL29Uh4PS6:b-v584gc)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488)*

**Comment by liangfok** [comment]
+@liangfok 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488#-:-KRssIDGh7T-1GT-6j3o:b-gyxe3j)*

**Comment by liangfok** [comment]
@maddog-tri if you give me write access to this branch of your fork, I can refine this for you. :smile: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488#-:-KRt4SblPA6fRd23DD9a:b-o0l6ve)*

**Comment by maddog-tri** [comment]
@jwnimmer-tri:  Thanks --- is the suggestion that I work those spellings into some kind of general cmake rules, or that I somehow use that cmake file verbatim itself, or that I just work those spellings into the drake_assert.h file?  In any case, before I start digging round at random, do you have any pointer/hint in mind to something similar in the codebase?

@liangfok:  Thanks for the offer, but this is an opportunity to (re)acquaint myself with the drake build system and the PR process.  I'm better off if I see it through to the end.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488#-:-KS-XFt-iTDaQr0hQ2hW:b-7u0e8p)*

**Comment by jwnimmer-tri** [comment]
> ... work those spellings into the drake_assert.h file...

This way would be the first thing I would try.

> ... do you have any pointer/hint in mind to something similar in the codebase?

There aren't that many preprocessor `#if`s in the code; you can just grep for some to find examples of platform-specific edits.

**Comment by maddog-tri** [comment]
@liangfok: This seems to work now --- please review.

+@sammy-tri  You're on-call today now, right?  Please review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488#-:-KS72F39PgMFYIyTa96T:brc4wfz)*

**Comment by liangfok** [comment]
Testing now using OSX....

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488#-:-KS756Iyfty-acBBr4mk:bx87fcp)*

**Comment by sammy-tri** [comment]
:lgtm: pending @liangfok's testing on OSX.  The jenkins build link is a little weird...  This did compile successfully on Windows, right?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488#-:-KS79b9D-jvZJSsnl8jx:b8yuwvj)*

**Comment by maddog-tri** [comment]
I had all blue balls earlier this morning... and now mousing over the tab, they turned gray (except for clang-ninja/debug). Yah, "little weird", indeed.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488#-:-KS7B69EWvKX8XlQVWBL:b-g5u9gh)*

**Comment by maddog-tri** [comment]
"Console Output" records SUCCESS for all --- I have the feeling that the 'dots' status is derived from some very-small individual-configuration-history-buffers, and this build has fallen off the back of those buffers (for all but the clang-ninja/debug).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488#-:-KS7BrDRlDmDlQso07cU:b-2mfk45)*

**Comment by liangfok** [comment]
OSX testing works. :lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3488#-:-KS7J55AUiRZyzNAVjUu:brq405d)*
