### PR TITLE
[meshcat] Fix Meshcat::StaticHtml()

### LINKED ISSUE #18342: Saving Meshcat static html results in a file that does not open
### What happened?

I generated a simulation and tried to save the resulting meshcat visualization as an html. When I try to open that file, nothing pops up and I repeatedly get the error `Uncaught (in promise) TypeError: viewer.handle_command_bytearray is not a function`. I got the same result when I tried to open the html file generated by `//geometry:meshcat_manual_test`.

cc @cohnt @RussTedrake 

### Version

55409b1e2130e895f2930baec246c8c04bdc723e

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

```shell
Uncaught TypeError: this.connection is undefined
    handle_gamepads file:///[path]/meshcat_static.html:71
    animate file:///[path]/meshcat_static.html:85

Uncaught (in promise) TypeError: viewer.handle_command_bytearray is not a function
    <anonymous> file:///[path]/meshcat_static.html:113
```

### PR DESCRIPTION
**Pull request by RussTedrake**
My recent meshcat changes broke the StaticHtml()
method. meshcat_manual_test revealed the problem but I failed to notice during my offending PR! I've fixed it upstream and this PR updates the meshcat SHA.

Also updates the gamepad logic to not throw an error due to not having a connection.

Resolves #18342.

+@mpetersen94 for feature review, please.

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18349#-:-NHkT_lM2a8SxLp6Ev82:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18349#-:-NHlhi5n5tI6suoZ7tMZ:btfqah9)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

Has any step been taken to help future reviewers recognize if this gets broken? Obviously, the manual test proved insufficient. Or is that because the static html simply wasn't opened?  I wonder if we can't open it *for* the user...

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18349#-:-NHy_RSqBfnfMmd-mkwx:bb2zlhr)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18349#-NHy_oH5EVHcMSmn5H_5):*
nit; When you merge this, call out the fact that you're updating meshcat -- it'll be a huge boon to release engineers.

**Review by RussTedrake — COMMENTED** [review]
For now I simply intend to be more vigilant about opening the static html in the manual test.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18349#-:-NHz0gYw-sAu7rXSancZ:b-pi1nkl)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),mpetersen94 (waiting on @RussTedrake)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18349#-NHy_oH5EVHcMSmn5H_5):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit; When you merge this, call out the fact that you're updating meshcat -- it'll be a huge boon to release engineers.
</blockquote></details>

Done.
