### PR TITLE
Update to use lcm 1.3.0 lcm-pod.

### PR DESCRIPTION
**Pull request by jhoare**
Update drake to build with new lcm-pod with lcm 1.3.0. 

Will need to be updated once https://github.com/RobotLocomotion/lcm-pod/pull/13 is merged.

### CODE REVIEW

**Comment by billhoffman** [comment]
test this please

**Comment by jhoare** [comment]
Build issue looks to be on Windows 64 bit system. It looks like the issue may be with the upstream lcm? 

@billhoffman Could you look at this? I don't have a windows system.

Relevant error is:
```
C:\projects\workspace\experimental\compiler\msvc-64\label\windows\externals\lcm\lcm\lcm-src\lcmgen\lcmgen.c(867): error C3688: invalid literal suffix 'PRId64'; literal operator or literal operator template 'operator ""PRId64' not found 
```

**Comment by billhoffman** [comment]
add to whitelist

**Comment by jhoare** [comment]
Appveyor failed to download pkg-config from dropbox it looks like. Could someone re-trigger it?

**Comment by RussTedrake** [comment]
seems like appveyor is having a consistent problem?
btw - just close and reopen to retrigger a build.

**Comment by jhoare** [comment]
I filed a bug related to AppVeyor: #1703  It looks to me like the drake004/006 build failures are unrelated to my changes.  On ran out of heap space and the other appears to be issue #1702

**Comment by RussTedrake** [comment]
lcm branch is merged.  can you update the sha pointer?

**Comment by jhoare** [comment]
Updated and squashed all the older commits.
