### PR TITLE
Make DrakeLcmParams an aggregate to fix relevant compilation errors

### PR DESCRIPTION
**Pull request by alexkaratarakis**
This type is constructed as an aggregate in drake_lcm.cc

```C++
DrakeLcm::DrakeLcm(std::string lcm_url)
    : DrakeLcm(DrakeLcmParams{.lcm_url = std::move(lcm_url)}) {}
```

```C++
DrakeLcm::DrakeLcm(std::string lcm_url, bool defer_initialization)
    : DrakeLcm(DrakeLcmParams{
          .lcm_url = std::move(lcm_url),
          .channel_suffix = {},
          .defer_initialization = defer_initialization}) {}
```

However, because there are constructors, the type is not
actually an aggregate, causing:

```
drake/lcm/drake_lcm.cc:75:16: error: no matching constructor for initialization of 'drake::lcm::DrakeLcmParams'
    : DrakeLcm(DrakeLcmParams{.lcm_url = std::move(lcm_url)}) {}
               ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drake/lcm/drake_lcm.cc:89:16: error: no matching constructor for initialization of 'drake::lcm::DrakeLcmParams'
    : DrakeLcm(DrakeLcmParams{
               ^             ~
```

MinRepro example:
```C++
struct MyInt
{
    MyInt() = default;
    MyInt(const MyInt&) = default;
    MyInt(MyInt&&) = default;
    MyInt& operator=(const MyInt&) = default;
    MyInt& operator=(MyInt&&) = default;

    int a;
};

int main()
{
    MyInt a{.a = 5}
    (void)a;
    return 0;
}

```

```
error: designated initializers cannot be used with a non-aggregate type ‘fixed_containers::MyInt’
   27 |     MyInt a{.a = 5};
      |                   ^
```

Caused by #17337

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Out of curiosity, which compiler or build flags show this error message?  Our Drake CI does not seem to have caught it.

**Comment by alexkaratarakis** [comment]
> Out of curiosity, which compiler or build flags show this error message? Our Drake CI does not seem to have caught it.

I am using clang-14 and g++11.
I was also surprised by the CI not catching it. Per the README:

> This directory contains software that enables LCM to be mocked. The ability to replace LCM with a mock is useful for unit testing purposes. For more information, see: https://github.com/RobotLocomotion/drake/issues/3546.

Probably a long shot, but is it possible the tests only use a mock of the class or `DrakeLcm` and thus mask the issue?

**Review by jwnimmer-tri — COMMENTED** [review]
@drake-jenkins-bot ok to test.

:lgtm: +(status: single reviewer ok).

I checked using godbolt for the min repro -- it's `--std=c++20` mode that causes this.  It works fine in C++17 mode.  Per #14670 we want to add C++20 to our CI, but we haven't turned it on yet.

Thanks for the fix!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17845#-:-NBJNmn98Z-Jl62IiPoC:bmbkjv9)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @alexkaratarakis)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Comment by alexkaratarakis** [comment]
Good catch! I am indeed using C++20, and per https://en.cppreference.com/w/cpp/language/aggregate_initialization , as of C++20 types are required to have `no user-declared or inherited constructors ` to count as aggregate.

**Comment by jwnimmer-tri** [comment]
By the way, thanks for the tips and ping about this.

As of #17943, Drake now supports building in C++20 mode (when using a sufficiently-new compiler), including CI coverage of same.
